trigger: none
  # branches:
  #   include:
  #     - main

variables:
  azureSubscription: 'arm-svc-con'
  acrName: 'acronlinestoredevuksouth001'             # without .azurecr.io
  aksCluster: 'aks-onlinestore-dev-uksouth-001'
  aksResourceGroup: 'rg-onlinestore-dev-uksouth-001'
  helmChartPath: './helmchart/'
  namespace: "default"

stages:
- stage: Deploy
  jobs:
  - job: HelmDeploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Getting AKS credentials..."
          az aks get-credentials --name $(aksCluster) --resource-group $(aksResourceGroup) --overwrite-existing

          echo "Installing Helm chart..."
          helm upgrade --install myapp $(helmChartPath) \
            --namespace default