trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'arm-svc-con'
  acrName: 'acronlinestoredevuksouth001'             # without .azurecr.io
  aksCluster: 'aks-onlinestore-dev-uksouth-001'
  namespace: 'default'
  aksResourceGroup: 'rg-onlinestore-dev-uksouth-001'
  helmChartPath: './helmchart/'

stages:
- stage: Deploy
  jobs:
  - job: HelmDeploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: Get AKS Credentials
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Getting AKS credentials..."
          az aks get-credentials --name $(aksCluster) --resource-group $(aksResourceGroup) --overwrite-existing

    - task: HelmDeploy@1
      displayName: Helm Upgrade/Install
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: $(azureSubscription)
        azureResourceGroup: $(aksResourceGroup)
        kubernetesCluster: $(aksCluster)
        namespace: $(namespace)
        command: upgrade
        chartType: FilePath
        chartPath: '$(helmChartPath)'
        releaseName: 'storeapp'
        install: true
        waitForExecution: true